Feature/storm
Bit-Nation/panthalassa pull request #95
Opened 2018-09-03 15:20 UTC by florianlenz

- changed panthalassa to use storm

closes #92 
closes #88 
closes #87 
closed #82

2018-09-04 13:32 UTC, borjantrajanoski requested changes

2018-09-04 13:32 UTC, borjantrajanoski commented on chat/test_utils.go
> +	dbPath, err := filepath.Abs(os.TempDir() + "/" + time.Now().String())
`time.Now().String()` creates a filename containing spaces and other potentially problematic characters which cause issues and make windows builds panic, we should switch to `.UnixNano()` or similar

>dbPath, err := filepath.Abs(os.TempDir() + "/" + fmt.Sprint(time.Now().UnixNano()))

2018-09-04 13:32 UTC, borjantrajanoski commented on dapp/dapp_storage_test.go
> +	dbPath, err := filepath.Abs(os.TempDir() + "/" + time.Now().String())
`time.Now().String()` creates a filename containing spaces and other potentially problematic characters which cause issues and make windows builds panic, we should switch to .UnixNano() or similar

>dbPath, err := filepath.Abs(os.TempDir() + "/" + fmt.Sprint(time.Now().UnixNano()))

2018-09-04 13:32 UTC, borjantrajanoski commented on dapp/module/db/storage_test.go
>  	dbPath, err := filepath.Abs(os.TempDir() + "/" + time.Now().String())
`time.Now().String()` creates a filename containing spaces and other potentially problematic characters which cause issues and make windows builds panic, we should switch to .UnixNano() or similar

>dbPath, err := filepath.Abs(os.TempDir() + "/" + fmt.Sprint(time.Now().UnixNano()))

2018-09-04 13:32 UTC, borjantrajanoski commented on db/dr_key_storage_test.go
> +	dbPath, err := filepath.Abs(os.TempDir() + "/" + time.Now().String())
`time.Now().String()` creates a filename containing spaces and other potentially problematic characters which cause issues and make windows builds panic, we should switch to .UnixNano() or similar

>dbPath, err := filepath.Abs(os.TempDir() + "/" + fmt.Sprint(time.Now().UnixNano()))

2018-09-04 13:32 UTC, borjantrajanoski commented on documents/call.go
> +	docID, k := data["doc_id"].(float64)
Maybe change to  `int` instead of `float64` or is there any specific reason why the `doc_id` should be `float64`?
>docID, k := data["doc_id"].(int)

2018-09-04 13:32 UTC, borjantrajanoski commented on documents/call.go
> +	docID, k := data["doc_id"].(float64)
Maybe change to `int` instead of `float64` or is there any specific reason why the `doc_id` should be `float64`?

>docID, k := data["doc_id"].(int)

2018-09-04 13:32 UTC, borjantrajanoski commented on queue/bolt_queue_storage_test.go
> +	dbPath, err := filepath.Abs(os.TempDir() + "/" + time.Now().String())
`time.Now().String()` creates a filename containing spaces and other potentially problematic characters which cause issues and make windows builds panic, we should switch to `.UnixNano()` or similar

>dbPath, err := filepath.Abs(os.TempDir() + "/" + fmt.Sprint(time.Now().UnixNano()))

2018-09-04 13:32 UTC, borjantrajanoski commented on dapp/module/message/message_test.go
> +	dbPath, err := filepath.Abs(os.TempDir() + "/" + time.Now().String())
`time.Now().String()` creates a filename containing spaces and other potentially problematic characters which cause issues and make windows builds panic, we should switch to `.UnixNano()` or similar

>dbPath, err := filepath.Abs(os.TempDir() + "/" + fmt.Sprint(time.Now().UnixNano()))

2018-09-05 03:55 UTC, florianlenz commented on documents/call.go
> +	docID, k := data["doc_id"].(float64)
int's are of type `float64`

2018-09-05 03:55 UTC, florianlenz commented on documents/call.go
> +	docID, k := data["doc_id"].(float64)
(I mean when you decode json in go)

2018-09-05 03:55 UTC, florianlenz commented on documents/call.go
> +	docID, k := data["doc_id"].(float64)
see other comment.

2018-09-05 12:34 UTC, borjantrajanoski commented on documents/call.go
> +	docID, k := data["doc_id"].(float64)
Maybe https://golang.org/pkg/encoding/json/#Decoder.UseNumber ?

2018-09-05 12:34 UTC, borjantrajanoski commented on documents/call.go
> +	docID, k := data["doc_id"].(float64)
Maybe https://golang.org/pkg/encoding/json/#Decoder.UseNumber ?

2018-09-05 18:44 UTC, borjantrajanoski approved these changes

2018-09-05 18:55 UTC, merged